apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: Loki
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: Tempo
          matcherRegex: "(?:_TraceId|_trace_id|trace_id|TraceId|traceid|traceId)[=:\\s\\[\"]+([a-fA-F0-9]{32})"
          name: TraceID
          url: "$${__value.raw}"
