apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: Tempo
    editable: true
    jsonData:
      nodeGraph:
        enabled: true
      search:
        hide: false
      tracesToLogsV2:
        datasourceUid: Loki
        spanStartTimeShift: "-2m"
        spanEndTimeShift: "2m"
        tags:
          - key: "service.name"
            value: "app"
        filterByTrace: true
        filterBySpan: false
        customQuery: true
        query: '{app="drive-api"} |= "$${__trace.id}"'
